# Generated by Django 6.0.5 on 2026-05-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
