# Generated by Django 6.0.5 on 2026-05-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Full Name')),
                ('otp', models.CharField(blank=True, max_length=6, null=True, verbose_name='OTP Code')),
                ('otp_expiry', models.DateTimeField(blank=True, null=True, verbose_name='OTP Expiry Time')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('ne', 'Nepali (नेपाली)')], default='en', max_length=2, verbose_name='Preferred Language')),
                ('is_customer', models.BooleanField(default=True, verbose_name='Is Customer')),
                ('is_operator', models.BooleanField(default=False, verbose_name='Is Operator')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff (Admin Access)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Account Created At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
    ]
